apiVersion: devops.alauda.io/v1alpha1
kind: PipelineTemplate
metadata:
  name: sayHelloWorld
  annotations:
    alauda.io/displayName.zh-CN: 你好
    alauda.io/displayName.en: Sync Image
    alauda.io/description.zh-CN: 你好模板。
    alauda.io/description.en: Sync image template. Synchronize a Image tag from the source repository to the target repository. If the source image or target image repository is a private repository (intranet address), ensure that Jenkins services are available in the same network.
    alauda.io/readme.zh-CN: 
    alauda.io/readme.en: 
    alauda.io/version: v0.1
    alauda.io/style.icon: 
  labels:
    category: sayHelloWorld
spec:
  engine: graph
  withSCM: false
  agent:
    label: docker
  options:
    timeout: 3600
  stages:
    - name: sayHelloWorld
      tasks:
        - name: sayHelloWorld
          type: alauda/sayHelloWorld
  arguments:
    - displayName:
        zh-CN: "客户信息"
        en: "user Info"
      items:
        - name: guesterName
          schema:
            type: string
          binding:
            - sayHelloWorld.args.guesterName
          display:
            type: string
            name:
              zh-CN: "来访人名称"
              en: "guester name"
          required: true